# Generated by Django 5.0.4 on 2024-08-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_repartidor_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='_numero_de_cuenta',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='_numero_de_enrutamiento',
        ),
    ]
